# Generated by Django 4.0.5 on 2022-06-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
