# Generated by Django 4.0.5 on 2022-06-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='context',
            new_name='content',
        ),
    ]
