# Generated by Django 4.0.5 on 2022-06-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
