# Generated by Django 2.2 on 2022-06-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_contactreq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactReq',
        ),
    ]
