# Generated by Django 2.2 on 2022-06-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactrequests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactreq',
            old_name='comment',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contactreq',
            name='first_name',
        ),
        migrations.AddField(
            model_name='contactreq',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
