# Generated by Django 4.0.5 on 2022-06-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactrequests', '0002_auto_20220630_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactreq',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
